# Generated by Django 5.1.3 on 2024-11-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('link_mapa', models.URLField(blank=True, null=True)),
                ('playlist_url', models.URLField(blank=True, null=True)),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='eventos/')),
            ],
        ),
    ]
