# Generated by Django 5.1.3 on 2024-11-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='nombre',
            new_name='content1_ciudad_lugar',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='descripcion',
            new_name='header_descripcion',
        ),
        migrations.AddField(
            model_name='evento',
            name='content1_direccion_lugar',
            field=models.CharField(default='No especificada', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='content1_hora',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='content1_lugar',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='content1_titulo',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='header_titulo',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
    ]
