# Generated by Django 5.1.3 on 2024-11-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_rename_nombre_evento_content1_ciudad_lugar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='ubicacion',
        ),
    ]
