# Generated by Django 5.1.3 on 2024-11-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_remove_evento_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='header_foto_fondo',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
