# Generated by Django 5.1.3 on 2024-11-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_evento_header_foto_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nombre',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='header_foto_fondo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
