# Generated by Django 5.1.3 on 2024-11-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_evento_nombre_alter_evento_header_foto_fondo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='content1_foto_fondo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
