# Generated by Django 5.1.3 on 2024-11-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_evento_content1_foto_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='galeria_foto1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='galeria_foto2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='galeria_foto3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='galeria_foto4',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
