# Generated by Django 5.1.3 on 2024-11-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_evento_galeria_foto1_evento_galeria_foto2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='slide_foto1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='slide_foto2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='slide_foto3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
